import sys
from pathlib import Path

import pandas as pd

sys.path.append(str(Path(__file__).resolve().parents[1]))
from config.settings import DATA_QUALITY_REPORT, PROCESSED_FILES, PROCESSED_REQUIRED_COLUMNS, RAW_FILES


PRIMARY_KEYS = {
    "parks": "park_id",
    "species": "species_id",
    "sightings": "sighting_id",
    "weather": "weather_id",
    "visitation": "visit_id",
    "wildlife_features": "sighting_id",
    "wildlife_features_enriched": "sighting_id",
}


def _pct(value: float) -> str:
    return f"{value:.1%}"


def check_processed_data() -> dict[str, dict]:
    results: dict[str, dict] = {}
    for name, path in PROCESSED_FILES.items():
        if name == "wildlife_features_enriched" and not path.exists():
            continue
        item = {
            "path": path,
            "rows": 0,
            "columns": 0,
            "failures": [],
            "warnings": [],
            "missing_pct": {},
            "duplicate_rows": None,
        }
        if not path.exists():
            item["failures"].append(f"Missing processed file: {path}")
            results[name] = item
            continue
        df = pd.read_csv(path)
        item["rows"] = len(df)
        item["columns"] = len(df.columns)
        item["duplicate_rows"] = int(df.duplicated().sum())
        if df.empty:
            item["failures"].append("Dataset is empty")
        missing_columns = sorted(set(PROCESSED_REQUIRED_COLUMNS[name]) - set(df.columns))
        if missing_columns:
            item["failures"].append(f"Missing required columns: {missing_columns}")
        key = PRIMARY_KEYS[name]
        if key in df.columns and df[key].duplicated().any():
            item["failures"].append(f"Duplicate primary key values in {key}")
        if "source" in df.columns and df["source"].isna().all():
            item["failures"].append("Source column is completely null")
        if name in {"sightings", "wildlife_features"}:
            lat_ok = df["decimal_latitude"].between(24, 50).all()
            lon_ok = df["decimal_longitude"].between(-125, -66).all()
            if not lat_ok or not lon_ok:
                item["failures"].append("Latitude/longitude values fall outside expected U.S. ranges")
        if name in {"sightings", "weather", "wildlife_features"}:
            date_column = "event_date" if name in {"sightings", "wildlife_features"} else "date"
            if pd.to_datetime(df[date_column], errors="coerce").isna().any():
                item["failures"].append(f"{date_column} contains unparseable dates")
        if "month" in df.columns and not pd.to_numeric(df["month"], errors="coerce").between(1, 12).all():
            item["failures"].append("Month values must be between 1 and 12")
        if "recreation_visits" in df.columns:
            visits = pd.to_numeric(df["recreation_visits"], errors="coerce")
            if (visits.dropna() < 0).any():
                item["failures"].append("Negative visitation values found")
        if name == "wildlife_features":
            weather_rate = df["weather_joined"].astype(str).str.lower().eq("true").mean()
            visitation_rate = df["visitation_joined"].astype(str).str.lower().eq("true").mean()
            item["weather_join_rate"] = weather_rate
            item["visitation_join_rate"] = visitation_rate
            if weather_rate < 0.05:
                item["warnings"].append("Weather join rate is low because sightings and weather years may not overlap.")
            if visitation_rate < 0.05:
                item["warnings"].append("Visitation join rate is low because sightings and visitation years may not overlap.")
        if name == "sightings":
            item["data_quality_flags"] = df["data_quality_flag"].value_counts(dropna=False).to_dict()
        item["missing_pct"] = {column: float(df[column].isna().mean()) for column in df.columns}
        results[name] = item
    write_quality_report(results)
    failed = [name for name, item in results.items() if item["failures"]]
    if failed:
        raise RuntimeError(f"Processed data quality checks failed for: {failed}")
    return results


def write_quality_report(results: dict[str, dict]) -> Path:
    raw_to_processed = {
        "parks": "nps_parks",
        "species": "nps_species_reference",
        "sightings": "gbif_occurrences",
        "weather": "noaa_weather_daily",
        "visitation": "nps_visitation_monthly",
    }
    raw_rows = {}
    for processed_name, raw_name in raw_to_processed.items():
        raw_path = RAW_FILES[raw_name]
        if raw_path.exists():
            raw_rows[processed_name] = len(pd.read_csv(raw_path))

    lines = [
        "# Data Quality Report",
        "",
        "Generated by `etl/quality_checks.py` after the Step 3 ETL pipeline.",
        "",
        "This report covers processed CSVs and the analysis-ready wildlife feature table. It does not claim that bounding-box occurrence records are inside official park boundaries.",
        "",
    ]
    total_failures = sum(len(item["failures"]) for item in results.values())
    lines.extend([f"Overall status: {'PASS' if total_failures == 0 else 'FAIL'}", ""])
    lines.extend(["## Raw To Processed Retention", ""])
    for name, raw_count in raw_rows.items():
        processed_count = results.get(name, {}).get("rows", 0)
        dropped = raw_count - processed_count
        if name == "species":
            lines.append(
                f"- `{name}`: {raw_count} NPSpecies reference rows -> {processed_count} target species rows "
                f"({dropped} non-target reference rows not carried into the Step 3 species dimension)"
            )
        else:
            lines.append(f"- `{name}`: {raw_count} raw rows -> {processed_count} processed rows ({dropped} dropped)")
    lines.append("")
    for name, item in results.items():
        lines.extend(
            [
                f"## {name}",
                "",
                f"Path: `{item['path']}`",
                f"Rows: {item['rows']}",
                f"Columns: {item['columns']}",
                f"Duplicate full rows: {item['duplicate_rows']}",
                "",
                "Failures:",
            ]
        )
        lines.extend([f"- {failure}" for failure in item["failures"]] or ["- None"])
        lines.append("")
        lines.append("Warnings:")
        lines.extend([f"- {warning}" for warning in item["warnings"]] or ["- None"])
        if name == "wildlife_features":
            lines.extend(
                [
                    "",
                    f"Weather join success rate: {_pct(item.get('weather_join_rate', 0.0))}",
                    f"Visitation join success rate: {_pct(item.get('visitation_join_rate', 0.0))}",
                ]
            )
        if name == "sightings" and "data_quality_flags" in item:
            lines.append("")
            lines.append("Data quality flag distribution:")
            for flag, count in item["data_quality_flags"].items():
                lines.append(f"- `{flag}`: {count}")
        lines.append("")
        lines.append("Missing value percentages:")
        for column, pct in item["missing_pct"].items():
            lines.append(f"- `{column}`: {_pct(pct)}")
        lines.append("")
    lines.extend(
        [
            "## Cleaning Summary",
            "",
            "- Raw files were read from `data/raw/` and written to `data/processed/`.",
            "- Fully duplicated rows were removed.",
            "- Dates, numeric coordinates, visitation counts, and weather measures were parsed into analysis-ready types.",
            "- Sightings without usable date or coordinates were dropped because they cannot support temporal or spatial analysis.",
            "- GBIF bounding-box records were retained and flagged rather than overclaimed as official in-park records.",
            "- Weather and visitation joins preserve wildlife sightings even when contextual data is unavailable.",
        ]
    )
    DATA_QUALITY_REPORT.write_text("\n".join(lines) + "\n")
    return DATA_QUALITY_REPORT


if __name__ == "__main__":
    check_processed_data()
    print(f"Data quality report written to {DATA_QUALITY_REPORT}")
