from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
EXTERNAL_DOCS_DIR = DATA_DIR / "external_docs"
DATABASE_DIR = PROJECT_ROOT / "database"
DATABASE_PATH = DATABASE_DIR / "wildwhere.db"
DOCS_DIR = PROJECT_ROOT / "docs"
RAW_VALIDATION_REPORT = DOCS_DIR / "raw_data_validation_report.md"
DATA_QUALITY_REPORT = DOCS_DIR / "data_quality_report.md"
DATE_ACCESSED = "2026-05-28"

TARGET_PARKS = [
    {
        "park_code": "YELL",
        "park_name": "Yellowstone National Park",
        "state": "WY/MT/ID",
        "latitude": 44.4280,
        "longitude": -110.5885,
        "area_acres": 2219790.71,
        "gbif_geometry": "POLYGON((-111.2 44.1,-109.8 44.1,-109.8 45.1,-111.2 45.1,-111.2 44.1))",
        "noaa_station_id": "USW00094173",
        "noaa_station_name": "Yellowstone Lake",
        "weather_station_distance_km": 18.5,
        "designation": "National Park",
        "official_url": "https://www.nps.gov/yell/index.htm",
        "description": "Yellowstone preserves geothermal features, large intact ecosystems, and wildlife habitat across Wyoming, Montana, and Idaho.",
    },
    {
        "park_code": "GRTE",
        "park_name": "Grand Teton National Park",
        "state": "WY",
        "latitude": 43.7904,
        "longitude": -110.6818,
        "area_acres": 310044.36,
        "gbif_geometry": "POLYGON((-111.1 43.4,-110.3 43.4,-110.3 44.1,-111.1 44.1,-111.1 43.4))",
        "noaa_station_id": "USC00486440",
        "noaa_station_name": "Moran 5WNW",
        "weather_station_distance_km": 10.5,
        "designation": "National Park",
        "official_url": "https://www.nps.gov/grte/index.htm",
        "description": "Grand Teton protects the Teton Range, Jackson Hole, alpine lakes, and wildlife habitat in northwestern Wyoming.",
    },
    {
        "park_code": "GLAC",
        "park_name": "Glacier National Park",
        "state": "MT",
        "latitude": 48.7596,
        "longitude": -113.7870,
        "area_acres": 1013126.39,
        "gbif_geometry": "POLYGON((-114.6 48.2,-113.1 48.2,-113.1 49.1,-114.6 49.1,-114.6 48.2))",
        "noaa_station_id": "USS0013A19S",
        "noaa_station_name": "Flattop Mountain",
        "weather_station_distance_km": 7.0,
        "designation": "National Park",
        "official_url": "https://www.nps.gov/glac/index.htm",
        "description": "Glacier protects mountain landscapes, forests, lakes, and habitat along the Crown of the Continent.",
    },
    {
        "park_code": "OLYM",
        "park_name": "Olympic National Park",
        "state": "WA",
        "latitude": 47.8021,
        "longitude": -123.6044,
        "area_acres": 922649.41,
        "gbif_geometry": "POLYGON((-124.8 47.3,-122.9 47.3,-122.9 48.4,-124.8 48.4,-124.8 47.3))",
        "noaa_station_id": "USS0023B18S",
        "noaa_station_name": "Buckinghorse",
        "weather_station_distance_km": 14.9,
        "designation": "National Park",
        "official_url": "https://www.nps.gov/olym/index.htm",
        "description": "Olympic protects temperate rainforest, glacier-capped mountains, and Pacific coastal ecosystems.",
    },
    {
        "park_code": "MORA",
        "park_name": "Mount Rainier National Park",
        "state": "WA",
        "latitude": 46.8797,
        "longitude": -121.7269,
        "area_acres": 236381.64,
        "gbif_geometry": "POLYGON((-122.2 46.6,-121.4 46.6,-121.4 47.1,-122.2 47.1,-122.2 46.6))",
        "noaa_station_id": "USC00456898",
        "noaa_station_name": "Rainier Paradise RS",
        "weather_station_distance_km": 10.4,
        "designation": "National Park",
        "official_url": "https://www.nps.gov/mora/index.htm",
        "description": "Mount Rainier protects the volcanic peak, subalpine meadows, old-growth forests, and surrounding wildlife habitat.",
    },
]

TARGET_SPECIES = [
    {
        "common_name": "Grizzly Bear",
        "scientific_names": ["Ursus arctos"],
    },
    {
        "common_name": "Black Bear",
        "scientific_names": ["Ursus americanus"],
    },
    {
        "common_name": "Moose",
        "scientific_names": ["Alces alces"],
    },
    {
        "common_name": "Elk",
        "scientific_names": ["Cervus canadensis", "Cervus elaphus"],
    },
    {
        "common_name": "Bison",
        "scientific_names": ["Bison bison"],
    },
    {
        "common_name": "Gray Wolf",
        "scientific_names": ["Canis lupus"],
    },
    {
        "common_name": "Mountain Goat",
        "scientific_names": ["Oreamnos americanus"],
    },
    {
        "common_name": "Bighorn Sheep",
        "scientific_names": ["Ovis canadensis"],
    },
    {
        "common_name": "Bald Eagle",
        "scientific_names": ["Haliaeetus leucocephalus"],
    },
    {
        "common_name": "Coyote",
        "scientific_names": ["Canis latrans"],
    },
]

TARGET_SCIENTIFIC_NAMES = sorted(
    {name for species in TARGET_SPECIES for name in species["scientific_names"]}
)
ACCEPTED_GBIF_NAME_PREFIXES = sorted(TARGET_SCIENTIFIC_NAMES + ["Bos bison"])

RAW_FILES = {
    "parks": RAW_DATA_DIR / "park_metadata.csv",
    "visitation": RAW_DATA_DIR / "visitation.csv",
    "sightings": RAW_DATA_DIR / "wildlife_sightings.csv",
    "weather": RAW_DATA_DIR / "weather.csv",
    "gbif_occurrences": RAW_DATA_DIR / "gbif_occurrences.csv",
    "nps_species_reference": RAW_DATA_DIR / "nps_species_reference.csv",
    "nps_parks": RAW_DATA_DIR / "nps_parks.csv",
    "nps_visitation_monthly": RAW_DATA_DIR / "nps_visitation_monthly.csv",
    "noaa_weather_daily": RAW_DATA_DIR / "noaa_weather_daily.csv",
    "weather_station_mapping": RAW_DATA_DIR / "weather_station_mapping.csv",
}

REQUIRED_COLUMNS = {
    "parks": [
        "park_code",
        "park_name",
        "state",
        "latitude",
        "longitude",
        "area_acres",
        "source",
    ],
    "visitation": [
        "visitation_id",
        "park_code",
        "year",
        "recreation_visits",
        "source",
    ],
    "sightings": [
        "sighting_id",
        "park_code",
        "gbif_id",
        "scientific_name",
        "event_date",
        "decimal_latitude",
        "decimal_longitude",
        "basis_of_record",
        "source",
    ],
    "weather": [
        "weather_id",
        "park_code",
        "station_id",
        "date",
        "tmax_c",
        "tmin_c",
        "precipitation_mm",
        "source",
    ],
    "gbif_occurrences": [
        "occurrence_id",
        "park_code",
        "park_name",
        "target_common_name",
        "scientific_name",
        "common_name",
        "event_date",
        "decimal_latitude",
        "decimal_longitude",
        "basis_of_record",
        "dataset_name",
        "institution_code",
        "country",
        "state_province",
        "coordinate_uncertainty",
        "license",
        "source",
        "source_url",
        "date_accessed",
        "location_filter_method",
    ],
    "nps_species_reference": [
        "park_name",
        "park_code",
        "category",
        "common_name",
        "scientific_name",
        "occurrence_status",
        "abundance",
        "nativeness",
        "record_status",
        "source",
        "source_url",
        "date_accessed",
        "license_usage_note",
    ],
    "nps_parks": [
        "park_code",
        "park_name",
        "state",
        "latitude",
        "longitude",
        "acres",
        "designation",
        "description",
        "official_url",
        "source",
        "source_url",
        "date_accessed",
        "license_usage_note",
    ],
    "nps_visitation_monthly": [
        "park_name",
        "park_code",
        "year",
        "month",
        "recreation_visits",
        "source",
        "source_url",
        "date_accessed",
        "license_usage_note",
    ],
    "noaa_weather_daily": [
        "station_id",
        "nearest_park",
        "park_code",
        "date",
        "temperature_max",
        "temperature_min",
        "precipitation",
        "snowfall",
        "wind_speed",
        "source",
        "source_url",
        "date_accessed",
        "license_usage_note",
    ],
    "weather_station_mapping": [
        "park_code",
        "park_name",
        "station_id",
        "station_name",
        "distance_km",
        "selection_method",
        "source",
        "source_url",
        "date_accessed",
        "license_usage_note",
    ],
}

STEP2_DATASETS = [
    "gbif_occurrences",
    "nps_species_reference",
    "nps_parks",
    "nps_visitation_monthly",
    "noaa_weather_daily",
    "weather_station_mapping",
]

PROCESSED_FILES = {
    "parks": PROCESSED_DATA_DIR / "parks_clean.csv",
    "species": PROCESSED_DATA_DIR / "species_clean.csv",
    "sightings": PROCESSED_DATA_DIR / "sightings_clean.csv",
    "weather": PROCESSED_DATA_DIR / "weather_clean.csv",
    "visitation": PROCESSED_DATA_DIR / "visitation_clean.csv",
    "wildlife_features": PROCESSED_DATA_DIR / "wildlife_features.csv",
    "wildlife_features_enriched": PROCESSED_DATA_DIR / "wildlife_features_enriched.csv",
}

PROCESSED_REQUIRED_COLUMNS = {
    "parks": [
        "park_id",
        "park_code",
        "park_name",
        "state",
        "latitude",
        "longitude",
        "acres",
        "designation",
        "official_url",
        "source",
    ],
    "species": [
        "species_id",
        "common_name",
        "scientific_name",
        "category",
        "source",
    ],
    "sightings": [
        "sighting_id",
        "occurrence_id",
        "park_id",
        "species_id",
        "scientific_name",
        "common_name",
        "event_date",
        "year",
        "month",
        "season",
        "time_of_day",
        "decimal_latitude",
        "decimal_longitude",
        "coordinate_uncertainty",
        "basis_of_record",
        "location_filter_method",
        "source",
        "license",
        "data_quality_flag",
    ],
    "weather": [
        "weather_id",
        "park_id",
        "station_id",
        "date",
        "temperature_max",
        "temperature_min",
        "temperature_avg",
        "precipitation",
        "snowfall",
        "wind_speed",
        "source",
    ],
    "visitation": [
        "visit_id",
        "park_id",
        "park_name",
        "year",
        "month",
        "recreation_visits",
        "crowd_level",
        "source",
    ],
    "wildlife_features": [
        "sighting_id",
        "park_id",
        "park_name",
        "state",
        "species_id",
        "common_name",
        "scientific_name",
        "category",
        "event_date",
        "year",
        "month",
        "season",
        "time_of_day",
        "decimal_latitude",
        "decimal_longitude",
        "coordinate_uncertainty",
        "temperature_max",
        "temperature_min",
        "temperature_avg",
        "precipitation",
        "snowfall",
        "wind_speed",
        "recreation_visits",
        "crowd_level",
        "basis_of_record",
        "location_filter_method",
        "data_quality_flag",
        "source",
        "weather_joined",
        "visitation_joined",
    ],
    "wildlife_features_enriched": [
        "sighting_id",
        "park_id",
        "park_name",
        "state",
        "species_id",
        "common_name",
        "scientific_name",
        "category",
        "event_date",
        "year",
        "month",
        "season",
        "time_of_day",
        "decimal_latitude",
        "decimal_longitude",
        "coordinate_uncertainty",
        "temperature_max",
        "temperature_min",
        "temperature_avg",
        "precipitation",
        "snowfall",
        "wind_speed",
        "recreation_visits",
        "crowd_level",
        "basis_of_record",
        "location_filter_method",
        "data_quality_flag",
        "source",
        "weather_joined",
        "visitation_joined",
        "search_result_count",
        "official_source_count",
        "area_context_count",
        "season_context_count",
        "time_context_count",
        "avg_serp_confidence_score",
        "top_mentioned_area",
        "top_mentioned_season",
        "top_mentioned_time_of_day",
        "has_official_context",
        "has_recent_context",
    ],
}
